baseURL = 'https://example.org/'
languageCode = 'en-us'
publishDir="docs"
theme = 'ananke'
title = 'Home'
canonifyurls = true
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
